### PR TITLE
Feat/helm chart ci

### PR DESCRIPTION
**Pull request by abelhoula**

### CODE REVIEW

**Comment by abelhoula** [comment]
related to : https://github.com/kube-green/kube-green/pull/411

**Comment by davidebianchi** [comment]
Thank you for the update! I think it's ok, but I should verify how it works with pages (and if it would be possible to have a single release with both the release and the chart helm). I will do it in the next few days

**Comment by henobi** [comment]
Since recently it is also possible to push the helm chart  to an OCI repository like github conatiner registry.
It simplifies the build and publishing process a lot and gh-pages and chart-releaser are not longer required.
We implemented it here for another project: https://github.com/espresso-lab/oidc-forward-auth-middleware/blob/main/.github/workflows/release-prod.yml#L61

Maybe it's helpful for you.

**Comment by davidebianchi** [comment]
Hi @abelhoula! Sorry for the really long delay, but finally I had the time to understand the desired workflow for the helm-chart publication. 
I aligned this PR with master and made some really small changes, now (when pipelines will be green) I will merge into main.
Thanks for the great work!

**Pull request merged**
