### PR TITLE
Add support for StatefulSets

### PR DESCRIPTION
**Pull request by furkansb**
This PR adds support for StatefulSets. Default behaviour is to suspend StatefulSets just like Deployments. To ensure backward compatibility, I can change it to not-suspend as default just like CronJobs. 

The functionality works the same as suspending Deployments as of now.

### CODE REVIEW

**Comment by davidebianchi** [comment]
Hi @furkansb, thank you for the PR! It is very complete.

Unfortunately, it comes at a time when we are changing how we manage resources to simplify the support of default ones (see PR #417, in which we are simplifying the support of default resources, which will be merged very soon).
This is part of the [milestone 1](https://github.com/kube-green/kube-green/milestone/1), where the goal is to support all types of resources. So, I guess that StatefulSet could be added as default managed resources, but I propose to you to change the implementation accordingly.
What do you think about it?

**Comment by tomkukral** [comment]
Hi, I like this change. Can it be merge to some "legacy" branch so we can use it?

**Comment by furkansb** [comment]
> Hi @furkansb, thank you for the PR! It is very complete.
> 
> Unfortunately, it comes at a time when we are changing how we manage resources to simplify the support of default ones (see PR #417, in which we are simplifying the support of default resources, which will be merged very soon). This is part of the [milestone 1](https://github.com/kube-green/kube-green/milestone/1), where the goal is to support all types of resources. So, I guess that StatefulSet could be added as default managed resources, but I propose to you to change the implementation accordingly. What do you think about it?

I think this makes a lot of sense, I just wan't aware of this new implementation. I'll probably close this PR and add support for statefulsets with the new method within a new PR. Thanks for the suggestions!

**Comment by furkansb** [comment]
How do you feel about merging this to a legacy branch though? @davidebianchi

**Comment by davidebianchi** [comment]
> I think this makes a lot of sense, I just wan't aware of this new implementation. I'll probably close this PR and add support for statefulsets with the new method within a new PR. Thanks for the suggestions!

Great! :)

With merging to a legacy branch do you mean to release a new version of kube-green with this changes? Yes, I could do that. But there is already a new release candidate with the new changes, it could be easier to add statefulset with the new strategy and to release a new rc with it, because there is some code added to support the backward compatibility with deployment and cronjob, and it should be added also for statefulset if it will be released.
I think we could release the new rc also today if the support to statefulset will be added. What do you think about, could this be good for you?

**Comment by furkansb** [comment]
@davidebianchi It seemed easy to add support for StatefulSets with the new method so here it is: https://github.com/kube-green/kube-green/pull/425

**Pull request closed without merging**
