### PR TITLE
fix selectors

### LINKED ISSUE #193: non-unique selectors
Installed from OLM v0.4.0.

When I apply sleepinfo I get:
```shell 
k apply -f sleep.yaml 
Error from server (InternalError): error when creating "sleep.yaml": Internal error occurred: failed calling webhook "vsleepinfo.kb.io": failed to call webhook: Post "https://kube-green-controller-manager-service.openshift-operators.svc:443/validate-kube-green-com-v1alpha1-sleepinfo?timeout=10s": dial tcp 10.200.6.18:9443: connect: connection refused
```

```shell

svc:

k get svc -n openshift-operators -o wide|grep -i green 
kube-green-controller-manager-metrics-service                 ClusterIP   10.201.156.118   <none>        8443/TCP   30m   control-plane=controller-manager
kube-green-controller-manager-service                         ClusterIP   10.201.246.36    <none>        443/TCP    30m   control-plane=controller-manager
kube-green-webhook-service                                    ClusterIP   10.201.200.165   <none>        443/TCP    30m   control-plane=controller-manager
```

controller logs:
```
k logs kube-green-controller-manager-c7d45f7d9-j7rm8
I0929 08:15:06.504306       1 request.go:601] Waited for 1.043179934s due to client-side throttling, not priority and fairness, request: GET:https://10.201.0.1:443/apis/batch/v1?timeout=32s
1.6644393097184074e+09  INFO    controller-runtime.metrics      Metrics server is starting to listen    {"addr": "127.0.0.1:8080"}
1.664439309718671e+09   INFO    controller-runtime.builder      skip registering a mutating webhook, object does not implement admission.Defaulter or WithDefaulter wasn't called       {"GVK": "kube-green.com/v1alpha1, Kind=SleepInfo"}
1.664439309718695e+09   INFO    controller-runtime.builder      Registering a validating webhook        {"GVK": "kube-green.com/v1alpha1, Kind=SleepInfo", "path": "/validate-kube-green-com-v1alpha1-sleepinfo"}
1.6644393097187605e+09  INFO    controller-runtime.webhook      Registering webhook     {"path": "/validate-kube-green-com-v1alpha1-sleepinfo"}
1.664439309718829e+09   INFO    setup   starting manager
1.6644393097190156e+09  INFO    controller-runtime.webhook.webhooks     Starting webhook server
1.664439309719225e+09   INFO    controller-runtime.certwatcher  Updated current TLS certificate
1.6644393097193158e+09  INFO    controller-runtime.webhook      Serving webhook server  {"host": "", "port": 9443}
1.6644393097193944e+09  INFO    Starting server {"path": "/metrics", "kind": "metrics", "addr": "127.0.0.1:8080"}
1.664439309719424e+09   INFO    Starting server {"kind": "health probe", "addr": "[::]:8081"}
1.6644393097194986e+09  INFO    controller-runtime.certwatcher  Starting certificate watcher
I0929 08:15:09.719558       1 leaderelection.go:248] attempting to acquire leader lease openshift-operators/2bd226ed.kube-green.com...
I0929 08:15:09.805968       1 leaderelection.go:258] successfully acquired lease openshift-operators/2bd226ed.kube-green.com
1.6644393098061695e+09  DEBUG   events  Normal  {"object": {"kind":"Lease","namespace":"openshift-operators","name":"2bd226ed.kube-green.com","uid":"6fd7faf6-386e-4f05-9d3d-2fbca6b1274a","apiVersion":"coordination.k8s.io/v1","resourceVersion":"995652687"}, "reason": "LeaderElection", "message": "kube-green-controller-manager-c7d45f7d9-j7rm8_5c57e8db-f880-4e84-9c1d-ac092562c620 became leader"}
1.6644393098063145e+09  INFO    Starting EventSource    {"controller": "sleepinfo", "controllerGroup": "kube-green.com", "controllerKind": "SleepInfo", "source": "kind source: *v1alpha1.SleepInfo"}
1.6644393098063338e+09  INFO    Starting Controller     {"controller": "sleepinfo", "controllerGroup": "kube-green.com", "controllerKind": "SleepInfo"}
1.6644393109079242e+09  INFO    Starting workers        {"controller": "sleepinfo", "controllerGroup": "kube-green.com", "controllerKind": "SleepInfo", "worker count": 10}
```

### PR DESCRIPTION
**Pull request by davidkarlsen**
Fixes #193 

Signed-off-by: David J. M. Karlsen <david@davidkarlsen.com>

### CODE REVIEW

**Comment by davidkarlsen** [comment]
@davidebianchi PTAL?

**Comment by davidkarlsen** [comment]
@davidebianchi The failing test does not seem related to my change?

**Comment by davidebianchi** [comment]
Hi @davidkarlsen, thank you for the PR!
I suppose the problem is due to the version of kind, which is not fixed. I try without the changes, but yes I don't think it's related to this PR

**Comment by davidkarlsen** [comment]
Great - can you release a version after merge - as the operator does not play well with other operators as it is now.

**Comment by davidebianchi** [comment]
Yes, sure. I will release a new version today or tomorrow

**Pull request merged**
